/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BirthCake: typeof import('./src/components/common/onlineResume/components/BirthCake/index.vue')['default']
    DegreeIcon: typeof import('./src/components/common/onlineResume/components/degreeIcon/index.vue')['default']
    DropDownlist: typeof import('./src/components/common/dropDownlist/index.vue')['default']
    Empty: typeof import('./src/components/common/empty/index.vue')['default']
    ExpIcon: typeof import('./src/components/common/onlineResume/components/expIcon/index.vue')['default']
    FemaleIcon: typeof import('./src/components/common/femaleIcon/index.vue')['default']
    Footer: typeof import('./src/components/common/footer/index.vue')['default']
    IndexJob: typeof import('./src/components/common/indexJob/index.vue')['default']
    JobList: typeof import('./src/components/common/jobList/index.vue')['default']
    MaleIcon: typeof import('./src/components/common/maleIcon/index.vue')['default']
    Navbar: typeof import('./src/components/common/navbar/index.vue')['default']
    OnlineResume: typeof import('./src/components/common/onlineResume/index.vue')['default']
    PositionCard: typeof import('./src/components/common/positionCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/common/search/index.vue')['default']
    StateIcon: typeof import('./src/components/common/onlineResume/components/stateIcon/index.vue')['default']
    UserInfoBox: typeof import('./src/components/common/userInfoBox/index.vue')['default']
  }
}
