export interface ICompanyData {
  id: number;
  company_id: string;
  company_name: string;
  logo: string;
  people_num: string;
  industry: string;
  financing: string;
  legal_representative: string;
  create_time: string;
  reg_city: string;
  region: string;
  detail_position: string;
  capital: string;
  state: string;
  business_scope: string;
  company_introduction: string;
  work_time: string;
  company_welfare: string;
  development: string;
  development_history: string;
  rest: string;
  others: string;
  addTime: string;
}
// export interface ICompanyData {
//   id: number;
//   company_id: string;
//   company_name: string;
//   logo: string;
//   people_num: string;
//   industry: string;
//   financing: string;
//   legal_representative: string;
//   create_time: string;
//   reg_city: string;
//   region: string;
//   detail_position: string;
//   capital: string;
//   state: string;
//   business_scope: string;
//   company_introduction: string;
//   work_time: string;
//   company_welfare: string;
//   development: string;
//   development_history: string;
//   rest: string;
//   others: string;
//   addTime: string;
//   position_id: string;
//   position_name: string;
//   salary: string;
//   cityName: string;
//   pos_region: string;
//   experiences: string;
//   degrees: string;
//   position_tag: string;
//   welfare_tag: string;
//   hr_id: string;
//   position_desc: string;
//   pos_addTime: string;
//   updateTime: string;
//   position_state: string;
//   position_type1: string;
//   position_type2: string;
//   job_type: string;
// }